# Blog settings
permalink: /blog/:title


# My variables
name: Deep::Blog
author_name: deepbug
description: my notes on programming and computer science...
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
